# Generated by Django 2.1.14 on 2019-11-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CauldronApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esuser',
            name='index',
        ),
        migrations.AddField(
            model_name='esuser',
            name='private',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CauldronApp.Dashboard'),
        ),
    ]
