# Generated by Django 3.1.2 on 2020-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauldronApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='githubrepository',
            options={'verbose_name_plural': 'GitHub repositories'},
        ),
        migrations.AlterModelOptions(
            name='gitlabrepository',
            options={'verbose_name_plural': 'GitLab repositories'},
        ),
        migrations.AlterModelOptions(
            name='gitrepository',
            options={'verbose_name_plural': 'Git repositories'},
        ),
        migrations.AlterModelOptions(
            name='meetuprepository',
            options={'verbose_name_plural': 'Meetup repositories'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name_plural': 'Repositories'},
        ),
        migrations.AlterField(
            model_name='meetuprepository',
            name='group',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='githubrepository',
            unique_together={('owner', 'repo')},
        ),
        migrations.AlterUniqueTogether(
            name='gitlabrepository',
            unique_together={('owner', 'repo')},
        ),
    ]
