# Generated by Django 3.1.2 on 2020-10-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CauldronApp', '0002_auto_20201026_1526'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='project',
            name='unique_project_name_user',
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('name', 'creator'), name='unique_project_name_user'),
        ),
    ]
