# Generated by Django 3.0.5 on 2020-05-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCompletedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daily Completed Tasks',
            },
        ),
        migrations.CreateModel(
            name='DailyCreatedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daily Created Projects',
            },
        ),
        migrations.CreateModel(
            name='DailyCreatedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daily Created Users',
            },
        ),
        migrations.CreateModel(
            name='DailyLoggedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Daily Logged Users',
            },
        ),
        migrations.CreateModel(
            name='MonthlyCompletedTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Monthly Completed Tasks',
            },
        ),
        migrations.CreateModel(
            name='MonthlyCreatedProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Monthly Created Projects',
            },
        ),
        migrations.CreateModel(
            name='MonthlyCreatedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Monthly Created Users',
            },
        ),
        migrations.CreateModel(
            name='MonthlyLoggedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Monthly Logged Users',
            },
        ),
    ]
